[package]
name = "exercise"
version = "0.1.0"
edition = "2021"
description = "My attempt at going through the google 3 day rust course"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
